version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      monthly-batch:
        patterns:
          - "*"
    cooldown:
      default-days: 60
      semver-major-days: 60
      semver-minor-days: 30
      semver-patch-days: 7
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      monthly-batch:
        patterns:
          - "*"
