// Auto-generated from the Vantage OpenAPI schema.
// Do not edit this file directly.

/** Date interval values supported by Vantage reports. */
export const VANTAGE_DATE_INTERVALS = [
  "this_month",
  "last_7_days",
  "last_30_days",
  "last_month",
  "last_3_months",
  "last_6_months",
  "custom",
  "last_12_months",
  "last_24_months",
  "last_36_months",
  "next_month",
  "next_3_months",
  "next_6_months",
  "next_12_months",
  "year_to_date",
  "last_3_days",
  "last_14_days",
] as const;

export type VantageDateInterval = (typeof VANTAGE_DATE_INTERVALS)[number];

/** Date bin values supported by Vantage cost reports. */
export const VANTAGE_DATE_BINS = ["cumulative", "day", "week", "month", "quarter", "hour"] as const;

export type VantageDateBin = (typeof VANTAGE_DATE_BINS)[number];

/** Cost aggregation dimensions supported by the Vantage costs query. */
export const VANTAGE_COST_AGGREGATIONS = ["cost", "usage", "count"] as const;

export type VantageCostAggregation = (typeof VANTAGE_COST_AGGREGATIONS)[number];

/** Chart types supported by Vantage cost reports. */
export const VANTAGE_CHART_TYPES = ["area", "line", "pie", "bar", "multi_bar"] as const;

export type VantageChartType = (typeof VANTAGE_CHART_TYPES)[number];

/** Network flow directions supported by Vantage. */
export const VANTAGE_NETWORK_FLOW_DIRECTIONS = ["all", "ingress", "egress"] as const;

export type VantageNetworkFlowDirection = (typeof VANTAGE_NETWORK_FLOW_DIRECTIONS)[number];

/** Network flow weighting dimensions supported by Vantage. */
export const VANTAGE_NETWORK_FLOW_WEIGHTS = ["costs", "bytes"] as const;

export type VantageNetworkFlowWeight = (typeof VANTAGE_NETWORK_FLOW_WEIGHTS)[number];

/** Built-in grouping dimensions supported by Vantage Financial Commitment reports. */
export const VANTAGE_FINANCIAL_COMMITMENT_GROUPINGS = [
  "cost_type",
  "commitment_type",
  "commitment_id",
  "service",
  "resource_account_id",
  "provider_account_id",
  "region",
  "cost_category",
  "cost_sub_category",
  "instance_type",
] as const;

export type VantageFinancialCommitmentGrouping =
  | (typeof VANTAGE_FINANCIAL_COMMITMENT_GROUPINGS)[number]
  | `tag:${string}`;

/** Built-in grouping dimensions supported by Vantage Kubernetes Efficiency reports. */
export const VANTAGE_KUBERNETES_EFFICIENCY_GROUPINGS = [
  "cluster_id",
  "namespace",
  "region",
  "labeled",
  "category",
  "pod",
] as const;

export type VantageKubernetesEfficiencyGrouping =
  | (typeof VANTAGE_KUBERNETES_EFFICIENCY_GROUPINGS)[number]
  | `label:${string}`;

/** Object types supported by the Vantage audit log filter. */
export const VANTAGE_AUDIT_LOG_OBJECT_TYPES = [
  "virtual_tag",
  "cost_report",
  "recommendation_commitment",
  "segment",
  "access_policy",
] as const;

export type VantageAuditLogObjectType = (typeof VANTAGE_AUDIT_LOG_OBJECT_TYPES)[number];
